### ISSUE TITLE
Where there is a shell, there is a way...

### ISSUE THREAD

**Issue by kvaps** [sp00f1ng/booty#15]
Hi, I'm considering to use booty to build pxe-bootable images for [kubernetes servers farm](https://github.com/kvaps/kubefarm).
I'm using [LTSP](https://github.com/ltsp/ltsp/) for many years, but booty seems even more lightweight and universal implementation.

I building my vmlinuz and initrd via Dockerfile from Ubuntu Focal like this:
https://github.com/kvaps/kubefarm/blob/d8c297d7971b78d115e83b7af2105d32e3ff2cb3/build/booty/Dockerfile#L133-L136

But after the boot I have lost myself somewhere on early initrd state:

![Screenshot_2020-07-26 OpenNebula Sunstone Cloud Operations Center(2)](https://user-images.githubusercontent.com/7556217/88474471-01da9d80-cf27-11ea-906e-12a5c54e09a0.png)
![image](https://user-images.githubusercontent.com/7556217/88474840-c215b500-cf2a-11ea-9bdc-149e4b7a4301.png)
![image](https://user-images.githubusercontent.com/7556217/88474831-add1b800-cf2a-11ea-91f5-b9de05782d74.png)

What am I doing wrong? How can I debug this?

**Comment by sp00f1ng** [comment]
как мы видим образ нашёлся, смонтировался, всё отлично, только вот /sbin/init почему-то не прошёл проверку -x (executable)

ls -lah /sbin/init с ним всё впорядке?

**Comment by sp00f1ng** [comment]
чтобы добавить ls в сборку, в /etc/booty/booty.conf добавьте ls в список SYSTEMWIDE_BINARIES=""
если она вам нужна.

**Comment by kvaps** [comment]
Да, всё верно, думаю эта проверка и не будет работать, там symlink на systemd с абсолютным путём:

```
root@d1046d57c7b6:/# ls -lah /rootfs/sbin/init
lrwxrwxrwx 1 root root 20 Jul  6 21:38 /rootfs/sbin/init -> /lib/systemd/systemd
```

**Comment by sp00f1ng** [comment]
ну я ставил арч, я не вникал в суть, но switch_root в Arch Linux происходил успешно, хотя там тоже systemd.

FROM ubuntu:20.04

это у вас убунту сервер какая-нибудь? я думаю должен взять её пощупать чтобы решить этот вопрос.

**Comment by sp00f1ng** [comment]
вам конечно же нужен squashfs / overlayfs?

пока вы можете, например, создать /init файл и вписать туда #!/lib/systemd/systemd, ядро выполнит этот init и запустит systemd.

перед тем как выполнить /usr/bin/mkinitramfs

echo "#!/lib/systemd/systemd" > /rootfs/init

затем /usr/bin/mkinitramfs /rootfs --standalone --output /initrd

но если вы нацелены на использование SquashFS + Overlay FS, тогда вам необходимо обязательно указывать опцию загрузки booty.use-overlayfs, потому что поведение по-умолчанию иное: оно распаковывает все оверлеи в tmpfs и загружается туда.

видите-ли, обычно предпочитают создавать ISO, и в grub.cfg я описал все допустимые варианты использования для удобства. люди просто выбирают нужный пункт меню, как на картинке.
![scrot](https://user-images.githubusercontent.com/66548199/88476605-cf02ca80-cf63-11ea-90b7-06814e79614a.png)

но просто знайте что для загрузки в Overlay FS нужно указывать booty.use-overlayfs

**Comment by kvaps** [comment]
> ну я ставил арч, я не вникал в суть, но switch_root в Arch Linux происходил успешно,

В арче симлинк относительный:
```console
# ls -lah /sbin/init
lrwxrwxrwx 1 root root 22 Jun 23 13:09 /sbin/init -> ../lib/systemd/systemd
```

**Comment by sp00f1ng** [comment]
последним коммитом добавил readlink -f /sbin/init, это не должно сломать обычный /sbin/init, но и симлинк тоже должен прочитаться. попробуйте.

**Comment by kvaps** [comment]
Спасибо, но я думаю что проблема возникает скорее на этой строке:
https://github.com/sp00f1ng/booty/blob/1d7953618b4e15684ca3cbc4bc762b6a51973da1/booty-init.in#L350
Так как абсолютный путь ведёт в `/lib/systemd/systemd` а не в `/newroot/lib/systemd/systemd`
И readlink тут не поможет, нужно либо запускать в chroot, либо подставлять префикс `/newroot`.

Я поиграюсь ещё с этим и пришлю PR

**Comment by sp00f1ng** [comment]
ну или смотрите, могу сделать /sbin/init переменной, которая передаётся ядру. и тогда по желанию вы могли бы сразу указывать init=/lib/systemd/systemd, минуя симлинк. будет $SWITCH_ROOTFS$INIT.

**Comment by kvaps** [comment]
Думаю это решение скорее будет workaround, лучше пофиксить проверку симлинков в chroot :)

**Comment by sp00f1ng** [comment]
ладно. мне главное чтобы у вас всё заработало. а там уже решим как лучше.

**Comment by kvaps** [comment]
Спасибо, я пока не за компом, вечером проверю, отпишусь )

**Comment by kvaps** [comment]
Окей, с симлинком разобрались, теперь загрузка прерывается на
```
vfs: Unable to mount root fs on unknown-block(0,0)
```
![image](https://user-images.githubusercontent.com/7556217/88487784-6ed24f80-cf88-11ea-8e1a-1e9c63891b9f.png)

**Comment by kvaps** [comment]
> сделал init= или booty.init=/lib/systemd/systemd

Попробовал `init=/bin/bash`, не работает, зависает на:
![image](https://user-images.githubusercontent.com/7556217/88488526-fff7f500-cf8d-11ea-94d1-abe137bc0ded.png)

**Comment by sp00f1ng** [comment]
добавил switch_root < /dev/console > /dev/console

теперь работает. =)

**Comment by kvaps** [comment]
думаю issue можно закрывать
